services:
  strapi:
    # Cambiado a string para solucionar el error de validación
    build: .
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_REPLY_TO: ${EMAIL_REPLY_TO}
      PRICE_IMPORT_TOKEN: ${PRICE_IMPORT_TOKEN}
      NEWSLETTER_API_TOKEN: ${NEWSLETTER_API_TOKEN}
      NODE_ENV: production
    volumes:
      - strapi-data:/opt/app/public/uploads
    ports:
      - "1337:1337"

volumes:
  strapi-data:
